<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- all the wheels -->
	<xacro:property name="wheel_length" value="0.025" />
    <xacro:property name="wheel_radius" value="0.03" />
    <xacro:property name="wheel_mass" value="0.027"/>
    <xacro:property name="wheel_damping" value="1.0"/>
    <xacro:property name="wheel_friction" value="1.0"/>
    <xacro:property name="wheel_max_effort" value="0.5"/>
    <xacro:property name="wheel_max_velocity" value="1.0"/>

	<!-- front left wheel -->
	<xacro:wheel_joint 
		name="front_left_wheel_joint" 
		parent="base_link" child="front_left_wheel_link" 
		xyz="${chassis_length/4} ${chassis_length/2 + wheel_length/2} 0" 
		side="left" damping="${wheel_damping}" friction="${wheel_friction}"
		max_effort="${wheel_max_effort}" max_velocity="${wheel_max_velocity}">
	</xacro:wheel_joint>
	
	<xacro:wheel_link 
		name="front_left_wheel_link"
		in_radius="${wheel_radius}"
		in_length="${wheel_length}"
		in_mass="${wheel_mass}">
	</xacro:wheel_link>

	<!-- front right wheel -->
	<xacro:wheel_joint 
		name="front_right_wheel_joint" 
		parent="base_link" child="front_right_wheel_link" 
		xyz="${chassis_length/4} -${chassis_length/2 + wheel_length/2} 0" 
		side="right" damping="${wheel_damping}" friction="${wheel_friction}" 
		max_effort="${wheel_max_effort}" max_velocity="${wheel_max_velocity}">
	</xacro:wheel_joint>
	
	<xacro:wheel_link 
		name="front_right_wheel_link"
		in_radius="${wheel_radius}"
		in_length="${wheel_length}"
		in_mass="${wheel_mass}">
	</xacro:wheel_link>

	<!-- rear left wheel -->
	<xacro:wheel_joint 
		name="rear_left_wheel_joint" 
		parent="base_link" child="rear_left_wheel_link" 
		xyz="-${chassis_length/4} ${chassis_length/2 + wheel_length/2} 0" 
		side="left" damping="${wheel_damping}" friction="${wheel_friction}"
		max_effort="${wheel_max_effort}" max_velocity="${wheel_max_velocity}">
	</xacro:wheel_joint>
	
	<xacro:wheel_link 
		name="rear_left_wheel_link"
		in_radius="${wheel_radius}"
		in_length="${wheel_length}"
		in_mass="${wheel_mass}">
	</xacro:wheel_link>

	<!-- rear right wheel -->
	<xacro:wheel_joint 
		name="rear_right_wheel_joint" 
		parent="base_link" child="rear_right_wheel_link" 
		xyz="-${chassis_length/4} -${chassis_length/2 + wheel_length/2} 0"
		side="right" damping="${wheel_damping}" friction="${wheel_friction}"
		max_effort="${wheel_max_effort}" max_velocity="${wheel_max_velocity}">
	</xacro:wheel_joint>
	
	<xacro:wheel_link 
		name="rear_right_wheel_link"
		in_radius="${wheel_radius}"
		in_length="${wheel_length}"
		in_mass="${wheel_mass}">
	</xacro:wheel_link>
</robot>