<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">

	<xacro:include filename="robot.include.xacro" />

	<!-- base link -->
	<link name="base_link">
	</link>


	<!-- chassis 
	  setting length/width/height as properties so we can do maths ops with them. 
	-->

	<!-- 300mm (x) 300mm (y) and 50mm (z) -->
	<xacro:property name="chassis_length" value="0.3" />
    <xacro:property name="chassis_width" value="0.3" />
    <xacro:property name="chassis_height" value="0.05" />

	<joint name="chassis_joint" type="fixed">
		<parent link="base_link"/>
		<child link="chassis_link"/>
		<origin xyz="-${chassis_length/2} 0 0"/>
	</joint>


	<link name="chassis_link">
		<visual>
			<!-- position chassis origin 1/2 chassis lenght relative to the link. -->
			<origin xyz = "${chassis_length/2} 0 ${chassis_height/2}"/>
			<geometry> 
				<box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
			</geometry>
			<material name="orange"/>
		</visual>

		<collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
	</link>

	<xacro:include filename="robot.wheels.xacro" />


	<xacro:include filename="robot.camera.xacro" />

	<xacro:include filename="robot.gazebo.xacro" />
</robot>