<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- all the wheels -->
	<xacro:property name="wheel_length" value="0.03" />
    <xacro:property name="wheel_radius" value="0.025" />
    <xacro:property name="wheel_mass" value="1.0"/>

	<!-- front left wheel -->
	<xacro:wheel_joint 
		name="front_left_wheel_joint" 
		parent="base_link" 
		child="front_left_wheel_link" 
		xyz="${chassis_length/4} ${chassis_length/2 + wheel_length/2} 0" 
		side="left">
	</xacro:wheel_joint>
	
	<xacro:wheel_link 
		name="front_left_wheel_link"
		in_radius="${wheel_radius}"
		in_length="${wheel_length}"
		in_mass="${wheel_mass}">
	</xacro:wheel_link>

	<!-- front right wheel -->
	<xacro:wheel_joint 
		name="front_right_wheel_joint" 
		parent="base_link" 
		child="front_right_wheel_link" 
		xyz="${chassis_length/4} -${chassis_length/2 + wheel_length/2} 0" 
		side="right">
	</xacro:wheel_joint>
	
	<xacro:wheel_link 
		name="front_right_wheel_link"
		in_radius="${wheel_radius}"
		in_length="${wheel_length}"
		in_mass="${wheel_mass}">
	</xacro:wheel_link>

	<!-- rear left wheel -->
	<xacro:wheel_joint 
		name="rear_left_wheel_joint" 
		parent="base_link" 
		child="rear_left_wheel_link" 
		xyz="-${chassis_length/4} ${chassis_length/2 + wheel_length/2} 0" 
		side="left">
	</xacro:wheel_joint>
	
	<xacro:wheel_link 
		name="rear_left_wheel_link"
		in_radius="${wheel_radius}"
		in_length="${wheel_length}"
		in_mass="${wheel_mass}">
	</xacro:wheel_link>

	<!-- rear right wheel -->
	<xacro:wheel_joint 
		name="rear_right_wheel_joint" 
		parent="base_link" 
		child="rear_right_wheel_link" 
		xyz="-${chassis_length/4} -${chassis_length/2 + wheel_length/2} 0"
		side="right">
	</xacro:wheel_joint>
	
	<xacro:wheel_link 
		name="rear_right_wheel_link"
		in_radius="${wheel_radius}"
		in_length="${wheel_length}"
		in_mass="${wheel_mass}">
	</xacro:wheel_link>
</robot>